### PR TITLE
[WIP] Big overhaul

### PR DESCRIPTION
**Pull request by carstenbauer**
This is a WIP PR to improve the user-facing interface (and documetation) of, primarily, `LIKWID.PerfMon`.

**Code**
* [x] one-based indexing
* [x] provide simplified interface
  * [x] `perfmon`
    * [x] multiple perf groups
  * [x] `@perfmon`
    * [ ] ~~keyword args for `autopin` etc.?~~
    * [x] multiple perf groups
* [x] CI
  * [x] check / overhaul / fix examples
    * [x] CPU
    * [x] GPU (and CPU+GPU)
  * [x] setup CI on N2

**Docs**
* [x] clarify examples wrt indices (not cpu ids, one-based)
* [x] multiple group example
* [x] multithreading example

**TODO before merge**
* [x] tests for `@perfmon_marker` / `perfmon_marker`
* [x] docs
  * [x] howto perfmon
* [x] `@nvmon` / `nvmon` 
  * [ ] tests 
* [ ] `@nvmon_marker` / `nvmon_marker`
* [x] Update example in README.md

### CODE REVIEW

**Comment by carstenbauer** [comment]
**Preview of the new simplified API**

Simple single-threaded example:
```julia
using LIKWID
using LinearAlgebra

const N = 10_000
const a = 3.141
const x = rand(N)
const y = rand(N)
const z = zeros(N)

metrics, events = @perfmon "FLOPS_DP" begin
    for i in eachindex(x, y)
        z[i] = a * x[i] * y[i]
    end
end

@show events["RETIRED_SSE_AVX_FLOPS_ALL"];
@show metrics["DP [MFLOP/s]"];
```
Output
```
events["RETIRED_SSE_AVX_FLOPS_ALL"] = 20000.0                                                                       
metrics["DP [MFLOP/s]"] = 1363.3126039898723
```

Simple multi-threaded example:
```julia
using LIKWID
using LinearAlgebra

const N = 10_000
const a = 3.141
const x = rand(N)
const y = rand(N)
const z = zeros(N)

metrics, events = @perfmon "FLOPS_DP" begin
    Threads.@threads for i in eachindex(x, y)
        z[i] = a * x[i] * y[i]
    end
end

@show getindex.(events, "RETIRED_SSE_AVX_FLOPS_ALL"); # vector of events corresponding to Julia threads
@show getindex.(metrics, "DP [MFLOP/s]");
```
Output:
```
getindex.(events, "RETIRED_SSE_AVX_FLOPS_ALL") = [5954.0, 5000.0, 5000.0, 5000.0]
getindex.(metrics, "DP [MFLOP/s]") = [0.3990529460355565, 0.3351133238457814, 0.3351133238457814, 0.3351133238457814]
```

Note that Julia threads automatically get pinned to (the cpu threads they are currently running on) to get reliable results. The function equivalent `perform(f, groupname; cpuids, autopin)` provides more options. 

(cc @antoine-levitt, @TomTheBear, @vchuravy)

**Comment by antoine-levitt** [comment]
That's very nice, thanks for doing this, will test once merged!

**Comment by TomTheBear** [comment]
There is a driver mismatch on the one CI node:
```
xxxxx@medusa ~ $ nvidia-smi 
Failed to initialize NVML: Driver/library version mismatch
```
This needs to be fixed by our admins.

**Comment by carstenbauer** [comment]
Thanks for the info. I'll also set up CI on Noctua 2 soon so that we test on two different systems, one with the daemon and one with the perf_events backend.

**Comment by carstenbauer** [comment]
docs preview: https://juliaperf.github.io/LIKWID.jl/previews/PR31

**Comment by vchuravy** [comment]
This is looking great!

**Comment by carstenbauer** [comment]
Will try to finish things next week before I record my JuliaCon talk :blush:

**Comment by carstenbauer** [comment]
Let's merge this (I'll fix CI / doc build on main because it's easier). Remaining things like `@nvmon_marker` will have to wait.

**Comment by carstenbauer** [comment]
@antoine-levitt Feel free to try out the `main` branch now. Would be great to have someone test it :)

**Comment by antoine-levitt** [comment]
Hm, I wanted to try this for a course I was giving but it's over now and I don't want to go back to it :-p but I'll definitely have a use for it at some point, it looks great!

**Pull request merged**
