### PR TITLE
JuliaLab GPU CI

### PR DESCRIPTION
**Pull request by carstenbauer**

### CODE REVIEW

**Comment by carstenbauer** [comment]
(Disclaimer: I have never worked with buildkite before.)

Alright, it seems like step 1, installing LIKWID, finishes just fine (`likwid-topology` etc. seem to work). However, in step 2, the Julia tests, `liblikwid` can't be found. AFAICT, the major reason for this is that both steps seem to be executed on different machines, e.g. `p6000.gpuci3.julia.csail.mit.edu` and `rtx4000.gpuci4.julia.csail.mit.edu`, despite the fact that I indicated that step 2 `depends_on` step 1. Is there a way to enforce the same machine here?

Another route may be to merge both steps, i.e. put the LIKWID install commands as a `command` block into the julia step. For this case, I couldn't yet figure out how to have the `command` executed before the plugin actions, i.e. the julia tests run before LIKWID is installed.

@maleadt you seem to have worked on the julia buildkite plugin. Can you help me here?

**Comment by carstenbauer** [comment]
(Hopefully) Final issue: I can't run `sudo modprobe msr` (`sudo` not found and `modprobe` not found).

**Comment by carstenbauer** [comment]
Output of `cat /proc/version`: `Linux version 5.4.0-80-generic (buildd@lcy01-amd64-028) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #90~18.04.1-Ubuntu SMP Tue Jul 13 19:40:02 UTC 2021`

**Comment by carstenbauer** [comment]
@vchuravy Any idea how to load msr?

**Comment by carstenbauer** [comment]
Apart from the msr issue we need to figure out a way to install CUDA. AFAICS, we can't use CUDA_jll alone since to compile LIKWID with `NVIDIA_INTERFACE=true` CUDA needs to be available. In particular we also need header files like `cupti.h` which CUDA_jll doesn't ship.

It's a bit difficult for me to setup a manual CUDA installation procedure as the runners / agents aren't regular ubuntu systems and I don't know much about them.

**Comment by maleadt** [comment]
If you need to compile against CUDA, you need `CUDA_full_jll`. We haven't figured out yet how `CUDA_jll` needs to load a correct version of CUDA, but the CUDA CI runners are also using a GPU docker image so a CUDA run-time environment is present there (i.e. without needing `CUDA_jll`).

About the `modprobe`: that's not possible, since you're running in a Docker container.

**Comment by carstenbauer** [comment]
> About the `modprobe`: that's not possible, since you're running in a Docker container.

Docker container might be a showstopper. Given that we now also have the GPU CI at FAU / Erlangen I've deactivated the buildkite webhook for now.



> If you need to compile against CUDA, you need `CUDA_full_jll`.

Out of curiosity, I figured that I might need something like this and even found `CUDA_full_jll` but it seems to only support windows? At least that's what https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl says.

**Comment by maleadt** [comment]
> Out of curiosity, I figured that I might need something like this and even found `CUDA_full_jll` but it seems to only support windows? At least that's what https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl says.

Where do you see that? Maybe it was just in the processes of uploading the other artifacts when you had a look, I released it a couple of hours ago.

**Comment by carstenbauer** [comment]
Oh, I see, I didn't check `src/wrappers` explicitly but just looked at the README.md. There it only mentions Windows.

> `CUDA_full_jll.jl` is available for the following platforms:
>
>    `Windows x86_64` (`x86_64-w64-mingw32`)

**Comment by carstenbauer** [comment]
Given that we have the NHR@FAU infrastructure I'll close this for now. (Feel free to revive.)

**Pull request closed without merging**
